name: beyond_flutter_cli
description: A powerful CLI tool for creating Flutter projects with Clean Architecture pattern
version: 0.2.0
homepage: https://github.com/beyondchasm/beyondFlutterCli
repository: https://github.com/beyondchasm/beyondFlutterCli

environment:
  sdk: '>=3.8.1 <4.0.0'

executables:
  beyond: beyond_flutter_cli

dependencies:
  args: ^2.5.0
  mason: ^0.1.0-dev.56
  path: ^1.8.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
